model_type: 'jtnn-fnl'

smiles_input_file: './examples/lipo.txt'
output_directory: '../results'
scorer_type: 'LogPTestCase'
num_epochs: 5

#Selection/Optimization params
optimizer_type: 'geneticoptimizer'
tourn_size: 15
mate_prob: 0.7
mutate_prob: 0.2
mutation_std: 1
max_clones: 1
optima_type: "maxima"
selection_type: "tournament"
elite_perc: 0

initial_pop_size: 50
max_population: 50

#Generative model parameters:
##FNL JTVAE specific
vocab_path: '../test/all_vocab.txt'
model_path: '../test/model.epoch-35'