model_type: 'jtnn-fnl'

smiles_input_file: './examples/LogP_AutoGrow/new_data.txt'
output_directory: './examples/LogP_AutoGrow/'
scorer_type: 'LogPTestCase'
num_epochs: 3

#Selection/Optimization params
optimizer_type: 'geneticoptimizer'
tourn_size: 15
mate_prob: 0.7
mutate_prob: 0.1
mutation_std: 1
max_clones: 1
optima_type: "maxima"
selection_type: "tournament"
elite_perc: 0

initial_pop_size: 100
max_population: 100

#FNL JTNN specific
vocab_path: './examples/LogP_JTVAE/all_vocab.txt'
model_path: './examples/LogP_AutoGrow4/model.epoch-35'